# Archivo con parametros de configuracion para conexion a base de datos
driver: pdo_mysql
host: localhost
port: 3306
dbname: siacolwe_2016montesori
user: siacolwe_stzef
password: NevNav9956
charset:  UTF8 
